### ISSUE TITLE
Support for newer psutil versions

### ISSUE THREAD

**Issue by vonker** [chris104957/django-carrot#101]
I was just looking to get started with this package as it looks great, but ran into a basic dependency issue related to the psutil version that is required. 

The requirements.txt shows:
`psutil==5.4.5` 

Updating this dependence to `psutil>=5.4.5` would make it easier to get started, as the 5.4.5 version has some issues regarding compiling on Windows platforms (see changelog here: https://github.com/giampaolo/psutil/blob/master/HISTORY.rst).

**Comment by chris104957** [comment]
No problem - fixed in 1.3.3
