### ISSUE TITLE
django-carrot.com down

### ISSUE THREAD

**Issue by bastiW** [chris104957/django-carrot#105]
The docs on django-carrot.com seem to be down 

```
404. That’s an error.

The requested URL / was not found on this server. That’s all we 
```

**Comment by chris104957** [comment]
Yep, the domain expired. You'll need to use the rtd domain instead:
https://django-carrot.readthedocs.io/

I'll update the package info as soon as I get a chance

**Comment by chris104957** [comment]
All references to the expired domain have now been removed - closing the issue
